name: MusicPlayer_Nusatech
options:
  minimumXcodeGenVersion: 2.10
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "15.0"

settings:
  IPHONEOS_DEPLOYMENT_TARGET: "15.0"
  MARKETING_VERSION: "1.3.3"
  CURRENT_PROJECT_VERSION: "14"

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    minorVersion: 5.2.2

targets:
  MusicPlayer_Nusatech:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: app/sources
        group: app
      - path: app/resources
        group: app
      - path: app/Info.plist
        group: app
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.musicplayer.nusatech"
      INFOPLIST_FILE: app/Info.plist
      MARKETING_VERSION: 1.3.3
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Domain
    entitlements:
      path: app/Debug.entitlements
      properties:
        com.apple.security.application-groups: group.com.musicplayer

  MusicPlayerTests:
    type: bundle.unit-test
    platform: iOS
    sources: [MusicPlayerTests]
    dependencies:
      - target: MusicPlayer_Nusatech
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MusicPlayer_Nusatech.app/MusicPlayer_Nusatech"
        BUNDLE_LOADER: "$(TEST_HOST)"

  Core:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.musicplayer.nusatech.core"
      INFOPLIST_FILE: core/Info.plist
    sources:
      - path: core/sources
        group: core
      - path: core/resources
        group: core
    dependencies:
      - package: Alamofire
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: Core_Tests
          parallelizable: true
          randomExecutionOrder: true

  Core_Tests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: core/CoreTests-Info.plist
    sources:
      - path: core/tests
        group: core
    dependencies:
      - target: Core
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: Core_Tests
          parallelizable: true
          randomExecutionOrder: true

  Domain:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.musicplayer.nusatech.domain"
      INFOPLIST_FILE: domain/Info.plist
    sources:
      - path: domain/sources
        group: domain
    dependencies:
      - target: Core
    scheme:
      gatherCoverageData: true
