# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :test do
    scan(
      scheme: "Core",
      clean: true,
      code_coverage: true,
      output_directory: "fastlane/test_output"
    )
  end

  desc "Build and distribute via Firebase"
  lane :deploy do
    gym(
      scheme: "App",
      clean: true
    )
    firebase_app_distribution(
      app: "your_firebase_app_id",
      testers: "your-email@example.com",
      release_notes: "New version"
    )
  end
end

